### PR TITLE
Make wrong file size fatal error optional

### PR DESCRIPTION
**Pull request by wd5gnr**
If the file is short, this change creates a warning instead of an error. The -s option causes it to fail instead of warn. If desired, you could easily reverse the sense of -s to make it nonfatal, although my preference is to make it a warning since I don't always fill a PIC or Atmel device.

Also removed the redundant short read messages and reduced repeated calls to getfilesize in the size checks.

Thanks!

### CODE REVIEW

**Comment by wd5gnr** [comment]
It looks like it won't let me make a new pull request while this one is open miniprohex (the shell script) doesn't quote device names which is a problem (I need to fix this in qtl886). If you don't get this, I'll have to branch on my side, roll out the changes on the size which you have not pulled and then make a new pull request just for that file.

**Comment by rozhuk-im** [comment]
You can use my fork: https://github.com/rozhuk-im/minipro
You can set file offset, flash offset, data size to read/write.

**Comment by timofonic** [comment]
@wd5gnr @vdudouyt @lkundrak @rozhuk-im @DavidGriffith Why another fork? What about merging upstream? THE MORE EYEBALLS, THE BETTER!

**Comment by DavidGriffith** [comment]
@rozhuk-im Would you please prepare a pull request to this repo incorporating your changes?

**Comment by rozhuk-im** [comment]
https://github.com/vdudouyt/minipro/issues/92#issuecomment-372035906

**Comment by DavidGriffith** [comment]
This pull request has been obviated by pull request #55.

**Pull request closed without merging**
