### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by bbb31**
I noticed that the README wasnt as intuitive and took some guess work to get the programmer to work. So, forked and updated for the system I'm on.

### CODE REVIEW

**Comment by chenz** [comment]
The existing compilation instructions are not specific to Debian 7 - only the note about libusb-1.0 installation from backports. Your compilation instructions for Ubuntu are virtually the same - no need to have them duplicated.

One could remove "fakeroot" and "dpkg-dev" from the dependencies in the existing instructions - these are only required for building the .deb package, and they are already mentioned in that section.

The part about the udev rules is helpful though. However - note that "make install" already installs the file... only in a location where it does not work automatically on Debian and related systems (same goes for the bash completion rules, and actually, I don't think it will work anywhere if installed under the default PREFIX of "/usr/local"). One can override these installation paths then calling "make install" (just like it is done in "debian/rules"), maybe that should be pointed out in the instructions.

**Comment by bbb31** [comment]
Some may not `make install` though; I do not `make install` because I do not like to pollute my system with src compiled packages.

**Comment by chenz** [comment]
After thinking about this some more, I'm proposing a change in #81 to have "make install" automatically detect the correct paths.

**Comment by bbb31** [comment]
I think the focus may be too much on the source compiling side. I have no issue source compiling; but, it's generally bad practice to source compile software and install it and run in it in a prod environment (these are users computers; so they are effectively prod). Instead of having the users source compile, just build the `deb` and upload it as a release to GH; this is a fairly normal thing to do. Keep the source compile docs for other *nix systems.

**Comment by timofonic** [comment]
@DavidGriffith What about this? What about merging with @rozhuk-im's fork and maybe even coordinate tasks like this? @bbb31 I think it's better to promote inclusion of the package in distros and find at least a maintainer for it, not providing tons of packages and make a mess and be limited to just a few "mainstream" ones (and geeks avoid them like a plague, FYI).

**Comment by DavidGriffith** [comment]
I'll manually apply the changes presented here to get around the conflicts Github is complaining about.  

For the other stuff, it's rather out of scope for this pull request, so I respectfully ask that someone open up an issue to discuss it.

**Pull request closed without merging**
